### ISSUE TITLE
Install Contour in IBM Cloud

### ISSUE THREAD

**Issue by datta-TG** [bitnami/bitnami-docker-contour#1]
# Install Contour in IBM Cloud

This documentation will guide you on how to install Contour on the IBM Cloud using the Kubernetes Service. Simple and effective.

## Pre-requisites

You must have an account created in IBM Cloud. The account needs to either be *Pay-As-You-Go* or *Subscription*. Click [here](https://cloud.ibm.com/docs/account?topic=account-accounts "here") to read more.
If you have a Lite account, you can upgrade it. Click [here](https://cloud.ibm.com/docs/account?topic=account-account-getting-started#account-gs-upgrade "here") to learn how to upgrade.

## Step 1: Provision Kubernetes Cluster

* Click on the search section at the top of the main page, type Kubernetes, and then choose Kubernetes Service.

![Kubernetes1](https://user-images.githubusercontent.com/70336951/105613296-a0896f00-5d8f-11eb-8223-fdd64b1c5c0d.PNG)

* In the new window, select between the free and standard type under "Pricing plan". Once selected, click on create.

![KubernetesPaid1](https://user-images.githubusercontent.com/70336951/105613305-aaab6d80-5d8f-11eb-8dc9-247420a9ab04.PNG)

We'll choose the Standard Plan for this documentation as the Free Plan may fall short of resources when deploying your pods. We highly recommend using a Standard Plan with the hardware that suits you the best. If you're selecting the Standard Plan, please make sure you select the adequate requirements,

* Select your Kubernetes Version to be the latest available or the required one by your application. In this example, we have set it to be '1.18.13'.
* Select Infrastructure as 'Classic'.
* Leave Resource Group to 'Default'.
* Select Geography to the one that suits you better or that fits your infrastructure.
* Select Availability to be 'Single Zone' or 'Multi Zone' depending on your needs.
* Select a Worker Zone that suits you better or that fits your infrastructure.

![KubernetesPaid2](https://user-images.githubusercontent.com/70336951/105613311-b434d580-5d8f-11eb-88ba-3dc83e1afd2c.PNG)

* Select the number of workers in Worker Pool.
* Give your Worker Pool a name.
* Leave the Encrypt Local Disk option 'On'
* Choose 'Both private and public endpoints' on Master Service Endpoint

![KubernetesPaid4](https://user-images.githubusercontent.com/70336951/105613313-bc8d1080-5d8f-11eb-9010-36b3fc72d7df.PNG)

* Give your cluster a name in 'cluster-name'
* Provide the tags to your cluster and click on Create.

![KubernetesPaid5](https://user-images.githubusercontent.com/70336951/105613316-c3b41e80-5d8f-11eb-995b-496faa87333d.PNG)

Wait a few minutes while your cluster is deployed.

![KubernetesPaid3](https://user-images.githubusercontent.com/70336951/105613319-cadb2c80-5d8f-11eb-9eb5-1f46790c3623.PNG)

The following checkmark and the word 'normal' will appear once the Kubernetes Cluster is deployed. You can check it under your cluster section which is located in your *Resources List*.

![KubernetesPaid6](https://user-images.githubusercontent.com/70336951/105613326-d75f8500-5d8f-11eb-97f5-43a746ed0888.PNG)

## Step 2:  Deploy IBM Cloud Block Storage plug-in

* Click on the search section at the top of the main page, select IBM Cloud Block Storage, and click on it.

![StoragePaid1](https://user-images.githubusercontent.com/70336951/105613331-e0e8ed00-5d8f-11eb-8224-2aad774762dd.PNG)

* A new window opens, select the cluster and enter the name you want for this workspace, in this case, it will be called _storage-example_, accept the terms, click *Install* and wait a few minutes.

![StoragePaid2](https://user-images.githubusercontent.com/70336951/105613461-9c118600-5d90-11eb-82e1-c9d3640b3503.PNG)

## Step 3: Install Contour

* Click on the search section at the top of the main page, type Contour, and click on it.

![contour1](https://user-images.githubusercontent.com/70336951/105613464-a469c100-5d90-11eb-99ba-4da4d2c64746.PNG)

* A new window opens, select the cluster and enter the name you want for the Contour workspace, in this case, it will be called _contour-example_, accept the terms and click on *Install*. You can modify the different installation parameters at the bottom. We will leave them by default as shown below, but you can read more about setting up the parameters [here](https://cloud.ibm.com/catalog/content/contour-Qml0bmFtaS1jb250b3Vy-global#about "here").

![contour2](https://user-images.githubusercontent.com/70336951/105613471-ad5a9280-5d90-11eb-9c00-d27d3e7f1d4d.PNG)

## Step 4: Verify Installation

* Go to *Resources List* in the Left Navigation Menu and click on *Kubernetes*.

![test1](https://user-images.githubusercontent.com/70336951/105613490-db3fd700-5d90-11eb-8e6e-79237752fee3.png)

* Click the *Actions* button and select *Web terminal*.

![test2](https://user-images.githubusercontent.com/70336951/105613498-e85cc600-5d90-11eb-881b-e512297d2218.PNG)

* A window opens to install the web terminal, click on install and wait a few minutes. The window will pop up at the buttom If the web terminal is already installed.

![test3](https://user-images.githubusercontent.com/70336951/105613503-f0b50100-5d90-11eb-8cd4-5063ccd1318a.PNG)

![test7](https://user-images.githubusercontent.com/70336951/105613508-f6124b80-5d90-11eb-94d8-6dda60162abd.PNG)

* Once you have installed the terminal, open it and type the following command. It will show you the workspaces of your cluster. You can see *contour-example* is now active.

`$ kubectl get ns`

![testcountour1](https://user-images.githubusercontent.com/70336951/105613514-00cce080-5d91-11eb-8171-0f45acb02155.PNG)

* You can then obtain more data about the service and it's pods.

`$ kubectl get pod -n NAMESERVICE -o wide`

![testcountour2](https://user-images.githubusercontent.com/70336951/105613517-06c2c180-5d91-11eb-9989-76c78c1f8e0a.PNG)

`$ kubectl get service -n NAME SERVICE`

![testcountour3](https://user-images.githubusercontent.com/70336951/105613519-0cb8a280-5d91-11eb-8e5e-9c58768033fc.PNG)

* Select the pod within your service using bash so you can start using Contour from the terminal.

`$ kubectl exec --stdin --tty PODNAME -n NAMESPACE -- /bin/bash`

![testcountour4](https://user-images.githubusercontent.com/70336951/105613526-14784700-5d91-11eb-9ab1-9a133f0c8085.PNG)

You have finished the installation, enjoy your Contour installation!

**Comment by carrodher** [comment]
Thanks for the info. As it seems that there is no issue we should take action and everything works properly, I am going to mark this issue as "Closed" so it can be used by other users looking for information as if it were documentation
