### ISSUE TITLE
Contour Release 1.21

### ISSUE THREAD

**Issue by CodeStaple** [bitnami/bitnami-docker-contour#2]
### Name and Version

bitnami/contour:1.21

### What is the problem this feature will solve?

Bitnami was not yet built the lastest version of Contour which released 1.21.0 13 days ago. It would be nice if Bitnami uplift the Contour Docker Image to the latest version of this application

### What is the feature you are proposing to solve the problem?

This would require Bitnami community to create a dockerfile build for the latest contour version

### What alternatives have you considered?

Due to the depth of dependency rebranding to bitnami, it is difficult for a new comer to build a new docker image from scratch. Current option is to build my own docker image and helm chart.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for asking for this.
  The new version is in our pipeline but we are facing some issues.
  It should be released soon.
